# Generated by Django 4.0.3 on 2022-07-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
